name: Linting

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install pip==$(sed -nE 's/pip = "==(.*)"/\1/p' Pipfile)
        pip install pipenv==$(sed -nE 's/pipenv = "==(.*)"/\1/p' Pipfile)
        pipenv install --system
    - name: Analysing the code with black
      run: |
        black $(git rev-parse --show-toplevel) --check
      continue-on-error: true
    - name: Analysing the code with flake8
      run: |
        flake8 $(git rev-parse --show-toplevel)
      continue-on-error: true
    - name: Analysing the code with isort
      run: |
        isort --check-only $(git rev-parse --show-toplevel)/ --profile black
      continue-on-error: true
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
      continue-on-error: true
    - name: Check for CRLF line endings
      run: |
        for file in $(git ls-files); do
          if grep -q $'\r$' "$file"; then
            echo "$file has faulty file endings"
          fi
        done
        if git grep -I --name-only $'\r'; then
          echo "CRLF line endings detected"
          exit 1
        fi
      continue-on-error: true
